sudo: false
language: node_js
node_js:
- 10 
cache: npm
script:
- hexo generate
deploy:
provider: pages
skip-cleanup: true
github-token: $GH_TOKEN
keep-history: true
# added
target_branch: master # generate static files to master
on:
branch: hexo-source # source code of hexo 
local-dir: public